allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  isolated-vm: true
  protobufjs: true
  sharp: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - isolated-vm
  - protobufjs
  - sharp
