import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { CUSTOMERS, PRODUCTS, PURCHASES } from './seed-data'

// Why this script exists: db/seed.ts seeds the *local* DB by running
// TRUNCATE … RESTART IDENTITY + INSERT against a writable connection
// string. That works locally, and works on Netlify when the runner has
// a writable connection string (Team Owner on production, Developer on
// a deploy-preview branch).
//
// For demos that don't have either of those — typically a `netlify init`
// site with no GitHub remote, where the only writable path into the
// production DB is via the auto-applied migration pipeline — we instead
// emit the seed data as an idempotent SQL migration. Drop the file in
// `netlify/database/migrations/`, commit, redeploy. Netlify's build
// extension applies it with internal credentials regardless of role.

const MIGRATIONS_DIR = 'netlify/database/migrations'
const MIGRATION_TAG = 'seed_demo_data'

function pgString(s: string): string {
  return "'" + s.replace(/'/g, "''") + "'"
}

function timestampPrefix(): string {
  // YYYYMMDDHHMMSS in UTC — same scheme drizzle-kit uses, so this seed
  // migration sorts after any schema migration generated today.
  const d = new Date()
  const pad = (n: number) => n.toString().padStart(2, '0')
  return [
    d.getUTCFullYear(),
    pad(d.getUTCMonth() + 1),
    pad(d.getUTCDate()),
    pad(d.getUTCHours()),
    pad(d.getUTCMinutes()),
    pad(d.getUTCSeconds()),
  ].join('')
}

function findExistingSeedMigration(): string | null {
  if (!existsSync(MIGRATIONS_DIR)) return null
  for (const entry of readdirSync(MIGRATIONS_DIR)) {
    if (entry.endsWith(`_${MIGRATION_TAG}`)) {
      return join(MIGRATIONS_DIR, entry)
    }
  }
  return null
}

type SeedBlock<T> = {
  table: string
  columns: ReadonlyArray<string>
  rows: ReadonlyArray<T>
  formatRow: (row: T, index: number) => string
}

function emitBlock<T>(lines: Array<string>, block: SeedBlock<T>): void {
  // Skip empty arrays — `INSERT … VALUES\nON CONFLICT …` with no rows is
  // invalid SQL, so a stripped-down seed-data.ts would otherwise produce
  // a migration that fails on apply.
  if (block.rows.length === 0) {
    lines.push(`-- Skipped ${block.table} block: no rows in db/seed-data.ts`)
    lines.push('')
    return
  }

  const cols = block.columns.map((c) => `"${c}"`).join(', ')
  lines.push(
    `INSERT INTO "${block.table}" (${cols}) OVERRIDING SYSTEM VALUE VALUES`,
  )
  lines.push(block.rows.map(block.formatRow).join(',\n'))
  lines.push('ON CONFLICT ("id") DO NOTHING;')
  lines.push(
    `SELECT setval(pg_get_serial_sequence('${block.table}', 'id'), GREATEST((SELECT COALESCE(MAX("id"), 0) FROM "${block.table}"), 1));`,
  )
  lines.push('')
}

function buildSQL(): string {
  const lines: Array<string> = [
    '-- Auto-generated by `pnpm db:seed:migration` from db/seed-data.ts.',
    '-- Idempotent: re-applying is a no-op (ON CONFLICT ("id") DO NOTHING).',
    '-- OVERRIDING SYSTEM VALUE is required because the schema declares',
    '-- the id columns as GENERATED ALWAYS AS IDENTITY; setval() at the',
    '-- end of each block advances the sequence past the seeded ids so',
    '-- subsequent app inserts allocate fresh ids without colliding.',
    '',
  ]

  emitBlock(lines, {
    table: 'customers',
    columns: ['id', 'name', 'email', 'city', 'joined'],
    rows: CUSTOMERS,
    formatRow: (c, i) =>
      `  (${i + 1}, ${pgString(c.name)}, ${pgString(c.email)}, ${pgString(c.city)}, ${pgString(c.joined)})`,
  })

  emitBlock(lines, {
    table: 'products',
    columns: ['id', 'name', 'category', 'price', 'stock'],
    rows: PRODUCTS,
    formatRow: (p, i) =>
      `  (${i + 1}, ${pgString(p.name)}, ${pgString(p.category)}, ${pgString(p.price)}, ${p.stock})`,
  })

  emitBlock(lines, {
    table: 'purchases',
    columns: ['id', 'customer_id', 'product_id', 'quantity', 'total', 'purchased_at'],
    rows: PURCHASES,
    formatRow: (p, i) =>
      `  (${i + 1}, ${p.customer_id}, ${p.product_id}, ${p.quantity}, ${pgString(p.total)}, ${pgString(p.purchased_at)})`,
  })

  return lines.join('\n')
}

function main() {
  if (!existsSync(MIGRATIONS_DIR)) {
    console.error(
      `${MIGRATIONS_DIR}/ does not exist.\n` +
        'Run `pnpm db:generate` first to create the schema migration, ' +
        'then re-run this script.',
    )
    process.exit(1)
  }

  const existing = findExistingSeedMigration()
  if (existing) {
    console.error(
      `A seed-data migration already exists at:\n  ${existing}\n\n` +
        'Re-running this script would create a duplicate that the migration ' +
        'runner applies in addition to the existing one. Either:\n' +
        '  • commit & deploy the existing one (it is idempotent — re-deploying\n' +
        '    will just be a no-op), or\n' +
        `  • \`rm -rf ${existing}\` and re-run this script to regenerate it\n` +
        '    from the current db/seed-data.ts.',
    )
    process.exit(1)
  }

  const dirName = `${timestampPrefix()}_${MIGRATION_TAG}`
  const dir = join(MIGRATIONS_DIR, dirName)
  mkdirSync(dir, { recursive: true })

  const file = join(dir, 'migration.sql')
  writeFileSync(file, buildSQL())

  console.log(`✓ Wrote ${file}`)
  console.log(
    `  ${CUSTOMERS.length} customers, ${PRODUCTS.length} products, ${PURCHASES.length} purchases`,
  )
  console.log('')
  console.log('Next:')
  console.log(`  git add ${dir}`)
  console.log('  git commit -m "Seed demo data via migration"')
  console.log('  netlify deploy --build --prod')
}

main()
